# Generated by Django 6.0.2 on 2026-03-11 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='first_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_en_tant_que_first', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='second_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conversation_en_tant_que_second', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_envoyes', to=settings.AUTH_USER_MODEL),
        ),
    ]
