# Generated by Django 6.0.2 on 2026-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='instagramm',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='profil',
            name='languages',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
    ]
